build.gradle, src/main/java/ddd/caffeine/ratrip/configuration/RedisConfiguration.java, src/main/resources/application.yml
=> Redis setting

build.gradle, src/main/java/ddd/caffeine/ratrip/common/configuration/QuerydslConfiguration.java, src/main/java/ddd/caffeine/ratrip/common/configuration/SecurityConfiguration.java, src/main/java/ddd/caffeine/ratrip/common/filter/JwtAuthenticationFilter.java, src/main/java/ddd/caffeine/ratrip/common/filter/JwtExceptionFilter.java, src/main/java/ddd/caffeine/ratrip/common/jpa/AuditingTimeEntity.java, src/main/java/ddd/caffeine/ratrip/module/auth/application/AuthServiceProvider.java, src/main/java/ddd/caffeine/ratrip/module/auth/presentation/AuthController.java, src/main/java/ddd/caffeine/ratrip/module/auth/presentation/dto/request/SignInRequestDto.java, src/main/java/ddd/caffeine/ratrip/module/auth/presentation/dto/request/SignOutRequestDto.java, src/main/java/ddd/caffeine/ratrip/module/auth/presentation/dto/request/SignUpRequestDto.java, src/main/java/ddd/caffeine/ratrip/module/auth/presentation/dto/request/TokenReissueRequestDto.java, src/main/java/ddd/caffeine/ratrip/module/place/model/Place.java, src/main/java/ddd/caffeine/ratrip/module/place/model/address/Address.java, src/main/java/ddd/caffeine/ratrip/module/user/domain/SocialInfo.java, src/main/java/ddd/caffeine/ratrip/module/user/domain/User.java, src/main/resources/application-dev.yml, src/main/resources/application.yml
- Querydsl 빌드 이슈(Issue #15)  에 대한 PR 입니다.
=> [RESOLVED] ISSUE #15

build.gradle
- plain.jar 파일 생성하지 않도록 하는 옵션 추가
=> hotfix(build.gradle): plain 파일 생성하지 않게 변경

src/main/java/ddd/caffeine/ratrip/common/configuration/SecurityConfiguration.java
클라이언트 단에서 API 서버에 요청 할 수 있도록 허용 해줍니다.
=> hotfix(SecurityConfiguration): Cors 특정 URI 허용

build.gradle
=> fix(build.gradle): Swagger 라이브러리 버전 다운그레이드

src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/PopularPlaceModel.java
- 추천 장소를 불러오는 과정에서 지도에 표시해야 하는 좌표 필드를 추가 하였습니다.
=> 추천 장소 API 응답값 중 좌표 추가

src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/PlaceKakaoData.java, src/main/java/ddd/caffeine/ratrip/module/place/model/Place.java, src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceDetailsResponseDto.java, src/main/resources/data-develop.sql, src/test/java/ddd/caffeine/ratrip/module/place/repository/PlaceRepositoryTest.java
=> hotfix: 장소 엔티티 additionalInfo 필드 추가

src/main/java/ddd/caffeine/ratrip/common/filter/JwtAuthenticationFilter.java, src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceDetailsByThirdPartyRequestDto.java
=> hotfix: id -> thirdPartyId 로 변경(클라이언트 - 가독성)

src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/PlaceKakaoModel.java, src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/search/PlaceSearchResponseDto.java
=> hotfix : 장소 검색 API 응답값 필드 추가

src/main/java/ddd/caffeine/ratrip/common/filter/JwtExceptionFilter.java
- 필터에서 엑세스 토큰을 통해 유저를 검증하는 단계에서 "존재하지 않는 유저" 예외를 잡을 수 있게 되었습니다.
=> feat(JwtExceptionFilter): 존재하지 않는 유저 예외 핸들링

src/main/java/ddd/caffeine/ratrip/common/jwt/JwtProvider.java
- 클라이언트의 개발 편의를 위한 엑세스 토큰 만료 기간 연장
=> temp(JwtProvider): Access Token 주기 일주일로 변경

src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java, src/main/java/ddd/caffeine/ratrip/common/exception/domain/DaySchedulePlaceException.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/day_schedule/DaySchedulePlaceService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/day_schedule/DaySchedulePlaceValidator.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/day_schedule/DayScheduleService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/DaySchedulePlace.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/repository/DaySchedulePlaceQueryRepository.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/repository/DaySchedulePlaceRepository.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/repository/implementation/DaySchedulePlaceQueryRepositoryImpl.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/TravelPlanController.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleAddPlaceRequestDto.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleExchangePlaceSequenceDto.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DaySchedulePlaceResponseDto.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleUpdatePlaceRequestDto.java
- 일정 내의 장소 정보를 수정 할 수 있습니다.
- 일정 내의 장소를 삭제 할 수 있습니다.
> 장소 정보 수정 (메모 수정)
> 일정 장소 삭제
=> 일정 내의 장소 수정 및 삭제 API

src/main/java/ddd/caffeine/ratrip/common/configuration/SecurityConfiguration.java
- swagger allow pattern 와일드 카드 사용
=> hotfix : swagger cors 문제

src/main/java/ddd/caffeine/ratrip/RatripServerApplication.java, src/main/java/ddd/caffeine/ratrip/common/configuration/SwaggerConfiguration.java
- 들어가는 URI 에 따른 swagger 서버 요청 URI 맞춤
=> hotfix : cors problem

src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanValidator.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/TravelPlan.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/TravelPlanController.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanResponseModel.java
- 진행중인 일정을 종료 할 수 있습니다.
- 클라이언트 개발할때 수월하도록 만든 임시 API 입니다.
=> 일정 종료 API 

src/main/java/ddd/caffeine/ratrip/module/place/domain/Place.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanUserService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/TravelPlanUserQueryRepository.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/implementation/TravelPlanUserQueryRepositoryImpl.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/TravelPlanController.java
- 종료된 최근 여행이 있어도 null 을 응답하는 문제가 있었습니다.
> 정상 동작 테스트입니다.
=> FIX : 최근 여행 불러오기 

src/main/java/ddd/caffeine/ratrip/module/place/application/PlaceService.java
- 북마크 정보를 가져오는 부분에서 place 가 저장되어있지 않은 상태에서 가져옴으로 버그 발생.
- 해당 부분 수정.
=> hotfix : bookmark 정보 가져오는 부분 버그 해결

src/main/java/ddd/caffeine/ratrip/module/place/application/PlaceService.java
- 장소 저장에서 다른 필드를 사용 하여 버그가 생겼습니다.
- 이를 수정하였습니다.
=> hotfix: 장소저장

src/main/java/ddd/caffeine/ratrip/module/place/domain/bookmark/BookmarkId.java
=> hotfix : @Embeddable 키워드 제거 

src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/day_schedule/DaySchedulePlaceService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/day_schedule/DayScheduleService.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/DaySchedulePlace.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/repository/DaySchedulePlaceQueryRepository.java, src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/repository/implementation/DaySchedulePlaceQueryRepositoryImpl.java
- 장소 삭제시 sequence 에 대한 동기화 처리에 문제가 있었습니다.
- 삭제 시 sequence 동기화 처리를 진행하였습니다.
> 정상 동작 테스트입니다.
=> 장소 일정 삭제시 Sequence 동기화 문제
